# Generated by Django 4.2.9 on 2024-01-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0002_customuser_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='time',
        ),
    ]
