# Generated by Django 4.2.9 on 2024-01-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[{'User', 'user'}, {'Staff', 'staff'}], max_length=50),
        ),
    ]
