# Generated by Django 4.2.9 on 2024-01-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff')], max_length=50),
        ),
    ]
