# Generated by Django 4.2.9 on 2024-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
