# Generated by Django 4.2.9 on 2024-01-26 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0010_remove_customuser_units_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
        migrations.AddField(
            model_name='unit',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
