# Generated by Django 4.2.9 on 2024-01-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0013_alter_unit_customer_alter_unit_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
