# Generated by Django 4.2.9 on 2024-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0014_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
