# Generated by Django 4.2.9 on 2024-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0017_alter_invoice_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='disconnection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
