# Generated by Django 4.2.9 on 2024-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0018_unit_disconnection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='previous_units',
            field=models.IntegerField(default=0),
        ),
    ]
