# Generated by Django 4.2.9 on 2024-01-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0019_unit_previous_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='previous_units',
        ),
    ]
