# Generated by Django 4.2.9 on 2024-01-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0020_remove_unit_previous_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
