# Generated by Django 4.2.9 on 2024-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0024_invoice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
