# Generated by Django 4.2.9 on 2024-01-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0025_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='staff',
        ),
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
