# Generated by Django 4.2.9 on 2024-01-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0026_remove_unit_customer_remove_unit_staff_unit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
