# Generated by Django 4.2.9 on 2024-01-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0028_unit_staff_alter_unit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
