# Generated by Django 4.2.7 on 2024-01-29 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0029_remove_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='previous_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='previous_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
