# Generated by Django 4.2.7 on 2024-01-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0032_unithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unithistory',
            name='unit',
        ),
    ]
