# Generated by Django 4.2.7 on 2024-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0034_alter_unithistory_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='unithistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
